### ISSUE TITLE
Loading of invalid method token

### ISSUE THREAD

**Issue by sakno** [ltrzesniewski/InlineIL.Fody#18]
Hi Lucas!

I found interesting issue when trying to obtain `RuntimeMethodHandle`:
```csharp
Ldtoken(PropertyGet(Type<IReadOnlyList<T>>(), "Item"));
Pop(out RuntimeMethodHandle handle);
var getter = MethodBase.GetMethodFromHandle(handle);
```
The exception is
> System.ArgumentException : Cannot resolve method Int64 get_Item(Int32) because the declaring type of the method handle System.Collections.Generic.IReadOnlyList`1[T] is generic. Explicitly provide the declaring type to GetMethodFromHandle.

There are two possible roots of this problem:
* Incorrect code gen by InlineIL
* Bug in CoreCLR

**Comment by sakno** [comment]
The method reference in IL inserted as
```il
instance !0 [netstandard]System.Collections.Generic.IReadOnlyList`1<!!T>::get_Item(int32)
```
Maybe it should be as follows:
```il
instance !!T [netstandard]System.Collections.Generic.IReadOnlyList`1<!!T>::get_Item(int32)
```

**Comment by sakno** [comment]
Closing this task, I found an issue: `GetMethodFromHandle` requires the second argument for the method handle obtained from the generic type.

**Comment by ltrzesniewski** [comment]
Hi,

I suppose you already figured it out, but given the error message, I'd expect the following to work (not tested though):

```C#
Ldtoken(PropertyGet(typeof(IReadOnlyList<>), "Item"));
```

**Comment by sakno** [comment]
Here is the correct code:
```csharp
Ldtoken(PropertyGet(Type<IReadOnlyList<T>>(), "Item"));
Pop(out RuntimeMethodHandle method);
Ldtoken(Type<IReadOnlyList<T>>());
Pop(out RuntimeTypeHandle type);
var getter = MethodBase.GetMethodFromHandle(method, type);
```
